### PR TITLE
Update to pass on 0.7

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by tknopp** [comment]
@c42f could you make a release including this. Currently this package cannot be installed on Julia 1.0.

**Comment by dpo** [comment]
Bump. @c42f Could you please review this? It's blocking for several of our packages. Thank you!

**Comment by c42f** [comment]
Release pending https://github.com/JuliaLang/METADATA.jl/pull/18526

I made you a collaborator @abelsiqueira in case you need to adjust things again while I'm not paying attention. If you want to make changes, that's cool — just keep the tests passing and give people a some time to comment on anything substantive :-)

**Comment by abelsiqueira** [comment]
Thanks!

**Comment by dpo** [comment]
Thank you @c42f !

**Pull request merged**
